# Generated by Django 5.0.1 on 2024-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('coach_level', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
    ]
