# Generated by Django 5.0.1 on 2024-02-05 19:01

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='time',
            field=django_jalali.db.models.jDateField(max_length=200),
        ),
    ]
