# Generated by Django 5.0.1 on 2024-02-05 19:06

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_gym_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='time',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
