# Generated by Django 5.0.1 on 2024-02-07 13:38

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_gym_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='gym',
            name='level',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='gym',
            name='time',
            field=models.CharField(max_length=250),
        ),
    ]
