# Generated by Django 5.0.1 on 2024-02-07 13:38

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_alter_gym_level_alter_gym_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='level',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gym',
            name='time',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
