# Generated by Django 4.2.4 on 2024-02-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_gym_level_alter_gym_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
